dbt-bq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: inlaid-keyword-311405 
      dataset: dbtcore
      threads: 1
      keyfile: /app/.secrets/inlaid-keyword-311405-033a1e9fcf98.json

dbt-postgress:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      user: postgres
      password: password
      port: 5432
      dbname: postgres
      schema: demo
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default