# Set base image (host OS)
FROM python:3.9.7-slim-bullseye

# pin poetry version here to ensure reproduceable builds
ENV POETRY_VERSION=1.1.13

# Install correct poetry version (without pip as suggested on
# poetry website)
RUN apt-get update \
    && apt-get install curl -y \
    && curl -sSL https://install.python-poetry.org | python - --version $POETRY_VERSION

ENV PATH="/root/.local/bin:$PATH"

# Set the working directory in the container
RUN mkdir /app
WORKDIR /app

# Copy the project and lock file here to cache dependencies in
# docker layers for faster rebuilds
COPY ./pyproject.toml /app/pyproject.toml
COPY ./poetry.lock /app/poetry.lock

# Install dependencies from pyproject
RUN poetry install --no-dev --no-interaction --no-ansi

# Copy the source and environmental variables
COPY ./src /app/src
COPY .env-ingest-prod /app/.env
COPY upheld-terminus-273921-9e190321e12f.json /app/upheld-terminus-273921-9e190321e12f.json

# Copy the entrypoint
COPY ./runner_ingest.py /app/runner.py
ENTRYPOINT ["poetry", "run", "python", "-u", "runner.py"]
